// React/src/App.tsx
import { useState, useMemo, useCallback } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.light.css';
import DataSource from 'devextreme/data/data_source';
import SelectBox, { type SelectBoxTypes } from 'devextreme-react/select-box';
import NumberBox, { type NumberBoxTypes } from 'devextreme-react/number-box';
import { DropDownGrid } from './components/drop-down-grid/DropDownGrid';
import { formatDisplayExpr, makeAsyncDataSource, searchExprOptions } from './appService';

function App(): JSX.Element {
  const [searchTimeout, setSearchTimeout] = useState(1000);

  const dataSource = useMemo(() => new DataSource({
    store: makeAsyncDataSource(),
    searchExpr: 'Employee',
  }), []);

  const dropDownBoxDataSource = useMemo(() => new DataSource({
    store: makeAsyncDataSource(),
  }), []);

  const onSearchExprChanged = useCallback((e: SelectBoxTypes.ValueChangedEvent) => {
    dataSource.searchExpr(e.value);
  }, [dataSource]);

  const onTimeoutChanged = useCallback((e: NumberBoxTypes.ValueChangedEvent) => {
    setSearchTimeout(e.value);
  }, [searchTimeout]);

  return (
    <div className="dx-viewport demo-container">
      <div className="row">
        <p>DropDownBox with search and embedded DataGrid</p>
        <DropDownGrid
          selectedRowKey={35709}
          dataSource={dataSource}
          dropDownBoxDataSource={dropDownBoxDataSource}
          searchTimeout={searchTimeout}
          displayExpr={formatDisplayExpr}
        />
      </div>

      <div className="options">
        <div className="caption">Search Options</div>
        <div className="option">
          <div>Search Expression</div>
          <SelectBox
            id="searchExpr"
            items={searchExprOptions}
            displayExpr="name"
            valueExpr="value"
            defaultValue="Employee"
            onValueChanged={onSearchExprChanged}
          />
        </div>
        <div className="option">
          <div>Search Timeout</div>
          <NumberBox
            id="searchTimeout"
            min={0}
            max={10000}
            value={searchTimeout}
            showSpinButtons={true}
            step={100}
            onValueChanged={onTimeoutChanged}
          />
        </div>
      </div>
    </div>
  );
}

export default App;

// Angular/src/app/app.component.ts
import {
  Component, inject,
} from '@angular/core';
import DataSource from 'devextreme/data/data_source';
import type { DxSelectBoxTypes } from 'devextreme-angular/ui/select-box';
import { AppService } from './app.service';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
  standalone: false,
})
export class AppComponent {
  private readonly appService = inject(AppService);

  readonly displayExpr = this.appService.formatDisplayExpr.bind(this.appService);

  searchExprOptions = [
    {
      name: '\'Employee\'',
      value: 'Employee',
    },
    {
      name: '[\'OrderNumber\', \'Employee\']',
      value: ['OrderNumber', 'Employee'],
    },
    {
      name: '[\'StoreCity\', \'Employee\']',
      value: ['StoreCity', 'Employee'],
    },
    {
      name: '[\'OrderNumber\',\'StoreCity\', \'StoreState\', \'Employee\']',
      value: ['OrderNumber', 'StoreCity', 'StoreState', 'Employee'],
    },
  ];

  selectedSearchExpr: string | string[] = 'Employee';

  searchTimeout = 1000;

  dataSource: DataSource;

  dropDownBoxDataSource: DataSource;

  constructor() {
    this.dataSource = new DataSource({
      store: this.appService.makeAsyncDataSource(),
      searchExpr: this.selectedSearchExpr,
    });

    this.dropDownBoxDataSource = new DataSource({
      store: this.appService.makeAsyncDataSource(),
    });
  }

  onSearchExprChanged(e: DxSelectBoxTypes.ValueChangedEvent): void {
    this.dataSource.searchExpr(e.value);
  }
}

<div class="dx-viewport demo-container">
  <div class="row">
    <p>DropDownBox with search and embedded DataGrid</p>
    <app-drop-down-grid
      [selectedRowKey]="35709"
      [dataSource]="dataSource"
      [dropDownBoxDataSource]="dropDownBoxDataSource"
      [searchTimeout]="searchTimeout"
      [displayExpr]="displayExpr"
    ></app-drop-down-grid>
  </div>

  <div class="options">
    <div class="caption">Search Options</div>
    <div class="option">
      <div>Search Expression</div>
      <dx-select-box
        id="searchExpr"
        [items]="searchExprOptions"
        displayExpr="name"
        valueExpr="value"
        [value]="selectedSearchExpr"
        (onValueChanged)="onSearchExprChanged($event)"
      >
      </dx-select-box>
    </div>

    <div class="option">
      <div>Search Timeout</div>
      <dx-number-box
        id="searchTimeout"
        [min]="0"
        [max]="10000"
        [(value)]="searchTimeout"
        [showSpinButtons]="true"
        [step]="100"
      >
      </dx-number-box>
    </div>
  </div>
</div>
